In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [3]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

## Preprocess the data
## Drop irrelevant features

In [4]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

## Geography and Gender are categorical 
## So Encode them

In [5]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [6]:
data.shape

(10000, 11)

## Geography pe thoda aur focus do label encoding mai three classes hai 0,1,2 , toh in number se effect padh sakta hai apne model pe
## So onehot encode it

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
one_hot_encoder=OneHotEncoder()
geo_encoder=one_hot_encoder.fit_transform(data[['Geography']])

In [9]:
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [10]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [11]:
one_hot_encoder.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [12]:
geo_encoded=pd.DataFrame(geo_encoder.toarray(),columns=one_hot_encoder.get_feature_names_out(['Geography']))
geo_encoded

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

## Combine one hot columns with the orginal data

In [13]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded],axis=1)

In [14]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

## save the encoders in pickle file

In [15]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
    
with open('one_hot_encoder.pkl','wb') as file:
    pickle.dump(one_hot_encoder,file)

## Divide the dataset into independent and dependent features

In [16]:
X=data.drop('Exited',axis=1)
Y=data['Exited']

In [17]:
## Split the data in training and testing sets
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [18]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [19]:
with open("Scaler.pkl" , "wb") as file:
    pickle.dump(scaler,file)

## ANN implementation

In [20]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

## Build our ANN model

In [21]:
X_train.shape

(8000, 12)

In [22]:
model=Sequential([Dense(64,activation='relu',input_dim=12),
                  Dense(32,activation='relu'),
                  Dense(1,activation='sigmoid')
                  ])

d:\GLOBAL_VENV\global_venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [23]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [25]:
opt=tf.keras.optimizers.Adam(learning_rate=0.01)
losses=tf.keras.losses.BinaryCrossentropy()

In [26]:
model.compile(optimizer=opt,loss=losses,metrics=['accuracy'])

## Setup the tensorboard

In [38]:
log_dir="logs/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

## Setup early stopping

In [39]:
early_stopping_callback=EarlyStopping(monitor='val_loss',verbose=True,restore_best_weights=True,patience=90)

In [40]:
model.fit(X_train,Y_train,epochs=400,validation_data=(X_test,Y_test),callbacks=[early_stopping_callback,tensorflow_callback])

Epoch 1/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8736 - loss: 0.3103 - val_accuracy: 0.8590 - val_loss: 0.3480
Epoch 2/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8780 - loss: 0.3065 - val_accuracy: 0.8540 - val_loss: 0.3576
Epoch 3/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8761 - loss: 0.3075 - val_accuracy: 0.8590 - val_loss: 0.3534
Epoch 4/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8752 - loss: 0.3053 - val_accuracy: 0.8570 - val_loss: 0.3561
Epoch 5/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8724 - loss: 0.3050 - val_accuracy: 0.8515 - val_loss: 0.3702
Epoch 6/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8742 - loss: 0.3056 - val_accuracy: 0.8615 - val_loss: 0.3644
Epoch 7/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8752 - loss: 0.3007 - val_accuracy: 0.8535 - val_loss: 0.3667
Epoch 8/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8774 - loss: 0.3027 - val_accuracy: 0.8500 - val_loss: 0.3637
Epoch 9/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8788 - loss: 0.2973 - val_accuracy: 0.8545 - val_loss: 0.3692
Epoch 10/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8801 - loss: 0.2987 - val_accuracy: 0.8485 - val_loss: 0.3756
Epoch 11/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8800 - loss: 0.2954 - val_accuracy: 0.8525 - val_loss: 0.3786
Epoch 12/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8801 - loss: 0.2923 - val_accuracy: 0.8570 - val_loss: 0.3703
Epoch 13/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8816 - loss: 0.2946 - val_accuracy: 0.8480 - val_loss: 0.3701
Epoch 14/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8854 - loss: 0.2894 - val_accuracy: 0.8565 - val_loss: 0.3724
Epoch 15/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8821 - loss: 0.2905 - val_accuracy: 0.8510 - val_loss: 0.3796
Epoch 16/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8831 - loss: 0.2857 - val_accuracy: 0.8580 - val_loss: 0.3716
Epoch 17/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8875 - loss: 0.2831 - val_accuracy: 0.8500 - val_loss: 0.3873
Epoch 18/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8873 - loss: 0.2820 - val_accuracy: 0.8500 - val_loss: 0.3828
Epoch 19/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8879 - loss: 0.2798 - val_accuracy: 0.8455 - val_loss: 0.4057
Epoch 20/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8886 - loss: 0.2797 - val_accuracy: 0.8585 - val_loss: 0.3749
Epoch 21/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8851 - loss: 0.2777 - val_accuracy: 0.8540 - val_loss: 0.3876
Epoch 22/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8881 - loss: 0.2773 - val_accuracy: 0.8525 - val_loss: 0.3919
Epoch 23/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8891 - loss: 0.2720 - val_accuracy: 0.8565 - val_loss: 0.3970
Epoch 24/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8901 - loss: 0.2772 - val_accuracy: 0.8535 - val_loss: 0.4013
Epoch 25/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8903 - loss: 0.2698 - val_accuracy: 0.8465 - val_loss: 0.4082
Epoch 26/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8903 - loss: 0.2685 - val_accuracy: 0.8565 - val_loss: 0.4068
Epoch 27/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8911 - loss: 0.2672 - val_accuracy: 0.8470 - val_loss: 0.4367
Epoch 28/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8919 - loss: 0.2661 - val_accuracy: 0.8535 - val_loss: 0.3970
Epoch 29/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8905 - loss: 0.2658 - val_accuracy: 0.8490 - val_loss: 0.4324
Epoch 30/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8913 - loss: 0.2628 - val_accuracy: 0.8485 - val_loss: 0.4365
Epoch 31/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8951 - loss: 0.2589 - val_accuracy: 0.8455 - val_loss: 0.4219
Epoch 32/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8969 - loss: 0.2568 - val_accuracy: 0.8510 - val_loss: 0.4395
Epoch 33/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8976 - loss: 0.2574 - val_accuracy: 0.8495 - val_loss: 0.4371
Epoch 34/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8978 - loss: 0.2521 - val_accuracy: 0.8510 - val_loss: 0.4279
Epoch 35/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8955 - loss: 0.2558 - val_accuracy: 0.8505 - val_loss: 0.4446
Epoch 36/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8997 - loss: 0.2527 - val_accuracy: 0.8490 - val_loss: 0.4478
Epoch 37/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8976 - loss: 0.2513 - val_accuracy: 0.8435 - val_loss: 0.4874
Epoch 38/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8976 - loss: 0.2510 - val_accuracy: 0.8460 - val_loss: 0.4583
Epoch 39/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9006 - loss: 0.2463 - val_accuracy: 0.8465 - val_loss: 0.4595
Epoch 40/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8945 - loss: 0.2490 - val_accuracy: 0.8535 - val_loss: 0.4691
Epoch 41/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8985 - loss: 0.2445 - val_accuracy: 0.8495 - val_loss: 0.4608
Epoch 42/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9014 - loss: 0.2436 - val_accuracy: 0.8485 - val_loss: 0.4767
Epoch 43/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9020 - loss: 0.2392 - val_accuracy: 0.8520 - val_loss: 0.4908
Epoch 44/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8982 - loss: 0.2423 - val_accuracy: 0.8445 - val_loss: 0.4754
Epoch 45/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9013 - loss: 0.2409 - val_accuracy: 0.8525 - val_loss: 0.5009
Epoch 46/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9038 - loss: 0.2379 - val_accuracy: 0.8490 - val_loss: 0.5164
Epoch 47/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9015 - loss: 0.2354 - val_accuracy: 0.8405 - val_loss: 0.5216
Epoch 48/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9035 - loss: 0.2317 - val_accuracy: 0.8445 - val_loss: 0.5046
Epoch 49/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9051 - loss: 0.2272 - val_accuracy: 0.8460 - val_loss: 0.5312
Epoch 50/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9071 - loss: 0.2226 - val_accuracy: 0.8420 - val_loss: 0.5325
Epoch 51/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9055 - loss: 0.2273 - val_accuracy: 0.8395 - val_loss: 0.5599
Epoch 52/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9047 - loss: 0.2284 - val_accuracy: 0.8410 - val_loss: 0.5621
Epoch 53/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9062 - loss: 0.2281 - val_accuracy: 0.8435 - val_loss: 0.5618
Epoch 54/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9044 - loss: 0.2241 - val_accuracy: 0.8475 - val_loss: 0.5522
Epoch 55/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9035 - loss: 0.2287 - val_accuracy: 0.8390 - val_loss: 0.5527
Epoch 56/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9061 - loss: 0.2257 - val_accuracy: 0.8400 - val_loss: 0.5732
Epoch 57/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9050 - loss: 0.2272 - val_accuracy: 0.8515 - val_loss: 0.5744
Epoch 58/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9076 - loss: 0.2254 - val_accuracy: 0.8465 - val_loss: 0.5615
Epoch 59/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9086 - loss: 0.2187 - val_accuracy: 0.8515 - val_loss: 0.5815
Epoch 60/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9081 - loss: 0.2183 - val_accuracy: 0.8430 - val_loss: 0.5712
Epoch 61/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9089 - loss: 0.2159 - val_accuracy: 0.8465 - val_loss: 0.5913
Epoch 62/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9080 - loss: 0.2213 - val_accuracy: 0.8440 - val_loss: 0.5759
Epoch 63/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9104 - loss: 0.2094 - val_accuracy: 0.8430 - val_loss: 0.6195
Epoch 64/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9128 - loss: 0.2061 - val_accuracy: 0.8440 - val_loss: 0.6163
Epoch 65/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9090 - loss: 0.2180 - val_accuracy: 0.8535 - val_loss: 0.5662
Epoch 66/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9053 - loss: 0.2210 - val_accuracy: 0.8425 - val_loss: 0.6150
Epoch 67/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9103 - loss: 0.2150 - val_accuracy: 0.8450 - val_loss: 0.6025
Epoch 68/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9124 - loss: 0.2093 - val_accuracy: 0.8455 - val_loss: 0.6189
Epoch 69/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9135 - loss: 0.2042 - val_accuracy: 0.8465 - val_loss: 0.6356
Epoch 70/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9114 - loss: 0.2058 - val_accuracy: 0.8525 - val_loss: 0.6267
Epoch 71/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9110 - loss: 0.2095 - val_accuracy: 0.8465 - val_loss: 0.6146
Epoch 72/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9125 - loss: 0.2055 - val_accuracy: 0.8450 - val_loss: 0.6573
Epoch 73/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9141 - loss: 0.2083 - val_accuracy: 0.8375 - val_loss: 0.6485
Epoch 74/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9158 - loss: 0.2030 - val_accuracy: 0.8425 - val_loss: 0.6094
Epoch 75/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9158 - loss: 0.2012 - val_accuracy: 0.8365 - val_loss: 0.6672
Epoch 76/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9172 - loss: 0.2000 - val_accuracy: 0.8465 - val_loss: 0.6934
Epoch 77/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9135 - loss: 0.2039 - val_accuracy: 0.8375 - val_loss: 0.6659
Epoch 78/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9140 - loss: 0.2047 - val_accuracy: 0.8510 - val_loss: 0.7087
Epoch 79/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9136 - loss: 0.2010 - val_accuracy: 0.8495 - val_loss: 0.6831
Epoch 80/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9156 - loss: 0.1984 - val_accuracy: 0.8430 - val_loss: 0.7043
Epoch 81/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9159 - loss: 0.1933 - val_accuracy: 0.8470 - val_loss: 0.7482
Epoch 82/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9154 - loss: 0.1973 - val_accuracy: 0.8425 - val_loss: 0.7437
Epoch 83/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9136 - loss: 0.2030 - val_accuracy: 0.8445 - val_loss: 0.6967
Epoch 84/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9179 - loss: 0.1937 - val_accuracy: 0.8360 - val_loss: 0.7255
Epoch 85/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9128 - loss: 0.2008 - val_accuracy: 0.8425 - val_loss: 0.7048
Epoch 86/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9180 - loss: 0.1927 - val_accuracy: 0.8435 - val_loss: 0.7068
Epoch 87/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9189 - loss: 0.1921 - val_accuracy: 0.8405 - val_loss: 0.7306
Epoch 88/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9194 - loss: 0.1886 - val_accuracy: 0.8500 - val_loss: 0.7341
Epoch 89/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9166 - loss: 0.1939 - val_accuracy: 0.8430 - val_loss: 0.7455
Epoch 90/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9166 - loss: 0.1978 - val_accuracy: 0.8420 - val_loss: 0.7541
Epoch 91/400
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9156 - loss: 0.1957 - val_accuracy: 0.8375 - val_loss: 0.7764
Epoch 91: early stopping
Restoring model weights from the end of the best epoch: 1.

In [41]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

## Load Tensorboard Extension

In [42]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [43]:
%tensorboard --logdir logs/fit20260315-124414

Reusing TensorBoard on port 6006 (pid 30600), started 0:01:40 ago. (Use '!kill 30600' to kill it.)